#pragma once

// === Character Set ===
#define TXT_CHARACTER_SET                               { 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', \
                                                          'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', \
                                                          'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', \
                                                          'Y', 'Z', \
                                                          '0', '1', '2', '3', '4', '5', '6', '7', \
                                                          '8', '9', \
                                                          '-', ' ' }

#define TXT_NOTE_NAMES                                  { "C", "C#", "D", "D#", "E", "F", "F#", \
                                                          "G", "G#", "A", "A#", "B" }

// === Glyphs in Tiny Font ===
#define GLYPH_TINY_PAUSE                               "\x01"
#define GLYPH_TINY_CLOCK                               "\x02"
#define GLYPH_TINY_THIN_ARROW_RIGHT                    "\x03"
#define GLYPH_TINY_THIN_ARROW_LEFT                     "\x04"
#define GLYPH_TINY_METRONOME_LEFT                      "\x05"
#define GLYPH_TINY_METRONOME_MIDDLE                    "\x06"
#define GLYPH_TINY_METRONOME_RIGHT                     "\x07"
#define GLYPH_TINY_BIG_ARROW_LEFT                      "\x08"
#define GLYPH_TINY_BIG_ARROW_DOWN                      "\x09"
#define GLYPH_TINY_BIG_ARROW_RIGHT                     "\x14"
#define GLYPH_TINY_BIG_ARROW_UP                        "\x0b"
#define GLYPH_TINY_PLAY_FORWARD_BACKWARD               "\x0c"
#define GLYPH_TINY_PLAY_LOOP                           "\x0d"
#define GLYPH_TINY_PLAY_FORWARD                        "\x0e"
#define GLYPH_TINY_PLAY_BACKWARD                       "\x0f"
#define GLYPH_TINY_PLAY_RANDOM                         "\x10"
#define GLYPH_TINY_STOP                                "\x11"
#define GLYPH_TINY_PLAY                                "\x12"
#define GLYPH_TINY_RECORD                              "\x13"
#define GLYPH_TINY_SMALL_ARROW_RIGHT                   "\x12"
#define GLYPH_TINY_SMALL_ARROW_LEFT                    "\x15"
#define GLYPH_TINY_SMALL_ARROW_DOWN                    "\x16"
#define GLYPH_TINY_SMALL_ARROW_UP                      "\x17"

// === Messages ===
#define TXT_MESSAGE_MIDI_DEVICE_CONNECTED               "USB MIDI DEVICE CONNECTED"
#define TXT_MESSAGE_MIDI_DEVICE_DISCONNECTED            "USB MIDI DEVICE DISCONNECTED"
#define TXT_MESSAGE_USER_SCALE_INITIALIZED              "USER SCALE INITIALIZED"
#define TXT_MESSAGE_USER_SCALE_COPIED                   "USER SCALE COPIED"
#define TXT_MESSAGE_USER_SCALE_PASTED                   "USER SCALE PASTED"
#define TXT_MESSAGE_USER_SCALE_SAVED                    "USER SCALE SAVED"
#define TXT_MESSAGE_USER_SCALE_LOADED                   "USER SCALE LOADED"
#define TXT_MESSAGE_TRACK_INITIALIZED                   "TRACK INITIALIZED"
#define TXT_MESSAGE_TRACK_COPIED                        "TRACK COPIED"
#define TXT_MESSAGE_TRACK_PASTED                        "TRACK PASTED"
#define TXT_MESSAGE_ALL_ROUTES_USED                     "All routes are used!"
#define TXT_MESSAGE_SETTINGS_INITIALIZED                "SETTINGS INITIALIZED"
#define TXT_MESSAGE_SETTINGS_SAVED                      "SETTINGS SAVED"
#define TXT_MESSAGE_SETTINGS_BACKED_UP                  "SETTINGS BACKED UP"
#define TXT_MESSAGE_SETTINGS_RESTORED                   "SETTINGS RESTORED"
#define TXT_MESSAGE_NO_SD_CARD_DETECTED                 "NO SD CARD DETECTED!"
#define TXT_MESSAGE_SD_CARD_FORMATTED                   "SD CARD FORMATTED"
#define TXT_MESSAGE_SONG_INITIALIZED                    "SONG INITIALIZED"
#define TXT_MESSAGE_ROUTE_SETTINGS_CONFLICT             "ROUTE SETTINGS CONFLICT WITH ROUTE %d"
#define TXT_MESSAGE_ROUTE_CHANGED                       "ROUTE CHANGED"
#define TXT_MESSAGE_PROJECT_INITIALIZED                 "PROJECT INITIALIZED"
#define TXT_MESSAGE_PROJECT_SAVED                       "PROJECT SAVED"
#define TXT_MESSAGE_PROJECT_LOADED                      "ROUTE CHANGED"
#define TXT_MESSAGE_PATTERN_INITIALIZED                 "PATTERN INITIALIZED"
#define TXT_MESSAGE_PATTERN_COPIED                      "PATTERN COPIED"
#define TXT_MESSAGE_PATTERN_PASTED                      "PATTERN PASTED"
#define TXT_MESSAGE_PATTERN_DUPLICATED                  "PATTERN DUPLICATED"
#define TXT_MESSAGE_SEQUENCE_INITIALIZED                "SEQUENCE INITIALIZED"
#define TXT_MESSAGE_SEQUENCE_COPIED                     "SEQUENCE COPIED"
#define TXT_MESSAGE_SEQUENCE_PASTED                     "SEQUENCE PASTED"
#define TXT_MESSAGE_SEQUENCE_DUPLICATED                 "SEQUENCE DUPLICATED"
#define TXT_MESSAGE_STEPS_INITIALIZED                   "STEPS INITIALIZED"
#define TXT_MESSAGE_STEPS_COPIED                        "STEPS COPIED"
#define TXT_MESSAGE_STEPS_PASTED                        "STEPS PASTED"
#define TXT_MESSAGE_STEPS_DUPLICATED                    "STEPS DUPLICATED"
#define TXT_MESSAGE_MIDI_OUTPUT_CHANGED                 "OUTPUT CHANGED"
#define TXT_MESSAGE_LAYOUT_CHANGED                      "LAYOUT CHANGED"

// === List Labels ===
#define TXT_LIST_LABEL_FORMAT_SD_CARD                   "Format SD card"
#define TXT_LIST_LABEL_NAME                             "Name"
#define TXT_LIST_LABEL_MODE                             "Mode"
#define TXT_LIST_LABEL_SHIFT_MODE                       "Shift Mode"
#define TXT_LIST_LABEL_INPUT_MODE                       "Input Mode"
#define TXT_LIST_LABEL_OUTPUT_MODE                      "Output Mode"
#define TXT_LIST_LABEL_SIZE                             "Size"
#define TXT_LIST_LABEL_TARGET                           "Target"
#define TXT_LIST_LABEL_MINIMUM                          "Min"
#define TXT_LIST_LABEL_MAXIMUM                          "Max"
#define TXT_LIST_LABEL_TRACKS                           "Tracks"
#define TXT_LIST_LABEL_SOURCE                           "Source"
#define TXT_LIST_LABEL_RANGE                            "Range"
#define TXT_LIST_LABEL_MIDI_SOURCE                      "MIDI Source"
#define TXT_LIST_LABEL_MIDI_EVENT                       "MIDI Event"
#define TXT_LIST_LABEL_CC_NUMBER                        "CC Number"
#define TXT_LIST_LABEL_NOTE                             "Note"
#define TXT_LIST_LABEL_NOTE_RANGE                       "Note Range"
#define TXT_LIST_LABEL_TEMPO                            "Tempo"
#define TXT_LIST_LABEL_SWING                            "Swing"
#define TXT_LIST_LABEL_OUTPUT_SWING                     "Output Swing"
#define TXT_LIST_LABEL_TIME_SIGNATURE                   "Time Signature"
#define TXT_LIST_LABEL_SYNC_MEASURE                     "Sync Measure"
#define TXT_LIST_LABEL_SCALE                            "Scale"
#define TXT_LIST_LABEL_ROOT_NOTE                        "Root Note"
#define TXT_LIST_LABEL_MONITOR_MODE                     "Monitor Mode"
#define TXT_LIST_LABEL_RECORD_MODE                      "Record Mode"
#define TXT_LIST_LABEL_MIDI_INPUT                       "MIDI Input"
#define TXT_LIST_LABEL_CVGATE_INPUT                     "CV/Gate Input"
#define TXT_LIST_LABEL_CURVECV_INPUT                    "Curve CV Input"
#define TXT_LIST_LABEL_EVENT                            "Event"
#define TXT_LIST_LABEL_GATE_SOURCE                      "Gate Source"
#define TXT_LIST_LABEL_NOTE_SOURCE                      "Note Source"
#define TXT_LIST_LABEL_VELOCITY_SOURCE                  "Vel. Source"
#define TXT_LIST_LABEL_CONTROL_NUMBER                   "Control Number"
#define TXT_LIST_LABEL_CONTROL_SOURCE                   "Control Source"
#define TXT_LIST_LABEL_PLAY_MODE                        "Play Mode"
#define TXT_LIST_LABEL_FILL_MODE                        "Fill Mode"
#define TXT_LIST_LABEL_MUTE_MODE                        "Mute Mode"
#define TXT_LIST_LABEL_FILL_MUTED                       "Fill Muted"
#define TXT_LIST_LABEL_CV_UPDATE_MODE                   "CV Update Mode"
#define TXT_LIST_LABEL_SLIDE_TIME                       "Slide Time"
#define TXT_LIST_LABEL_OCTAVE                           "Octave"
#define TXT_LIST_LABEL_OCTAVE_PLURAL                    "Octaves"
#define TXT_LIST_LABEL_OFFSET                           "Offset"
#define TXT_LIST_LABEL_TRANSPOSE                        "Transpose"
#define TXT_LIST_LABEL_ROTATE                           "Rotate"
#define TXT_LIST_LABEL_GATE_PROBABILITY_BIAS            "Gate P. Bias"
#define TXT_LIST_LABEL_GATE_RETRIGGER_PROBABILITY_BIAS  "Retrig P. Bias"
#define TXT_LIST_LABEL_GATE_LENGTH_BIAS                 "Length Bias"
#define TXT_LIST_LABEL_GATE_NOTE_PROBABILITY_BIAS       "Note P. Bias"
#define TXT_LIST_LABEL_GATE_SHAPE_PROBABILITY_BIAS      "Shape P. Bias"
#define TXT_LIST_LABEL_FIRST_STEP                       "First Step"
#define TXT_LIST_LABEL_LAST_STEP                        "Last Step"
#define TXT_LIST_LABEL_RUN_MODE                         "Run Mode"
#define TXT_LIST_LABEL_DIVISOR                          "Divisor"
#define TXT_LIST_LABEL_INPUT_DIVISOR                    "Input Divisor"
#define TXT_LIST_LABEL_OUTPUT_DIVISOR                   "Output Divisor"
#define TXT_LIST_LABEL_RESET_MEASURE                    "Reset Measure"
#define TXT_LIST_LABEL_GATE_LENGTH                      "Gate Length"
#define TXT_LIST_LABEL_HOLD                             "Hold"
#define TXT_LIST_LABEL_ARPEGGIATOR                      "Arpeggiator"
#define TXT_LIST_LABEL_RETRIGGER                        "Retrigger"
#define TXT_LIST_LABEL_MOD_RANGE                        "Mod Range"
#define TXT_LIST_LABEL_PITCH_BEND                       "Pitch Bend"
#define TXT_LIST_LABEL_HIGH_NOTE                        "High Note"
#define TXT_LIST_LABEL_LOW_NOTE                         "Low Note"
#define TXT_LIST_LABEL_NOTE_PRIORITY                    "Note Priority"
#define TXT_LIST_LABEL_VOICE_CONFIG                     "Voice Config"
#define TXT_LIST_LABEL_VOICES                           "Voices"
#define TXT_LIST_LABEL_TRACK                            "Track%d"
#define TXT_LIST_LABEL_ITEM                             "Item%d"
#define TXT_LIST_LABEL_GATE_VALUE                       "Gate%d"
#define TXT_LIST_LABEL_CV_VALUE                         "CV%d"
#define TXT_LIST_LABEL_FILE                             "%d: %s"
#define TXT_LIST_LABEL_EMPTY                            "(empty)"
#define TXT_LIST_LABEL_OUTPUT_PULSE                     "Output Pulse"
#define TXT_LIST_LABEL_MIDI_RX                          "Midi RX"
#define TXT_LIST_LABEL_MIDI_TX                          "Midi TX"
#define TXT_LIST_LABEL_USB_RX                           "USB RX"
#define TXT_LIST_LABEL_USB_TX                           "USB TX"
#define TXT_LIST_LABEL_PLAY                             "Play"
#define TXT_LIST_LABEL_PLAY_TOGGLE                      "Play Toggle"
#define TXT_LIST_LABEL_RECORD                           "Record"
#define TXT_LIST_LABEL_RECORD_TOGGLE                    "Record Toggle"
#define TXT_LIST_LABEL_TAP_TEMPO                        "Tap Tempo"
#define TXT_LIST_LABEL_NONE                             "None"
#define TXT_LIST_LABEL_MUTE                             "Mute"
#define TXT_LIST_LABEL_FILL                             "Fill"
#define TXT_LIST_LABEL_FILL_AMOUNT                      "Fill Amount"
#define TXT_LIST_LABEL_PATTERN                          "Pattern"
#define TXT_LIST_LABEL_CV_IN_VALUE                      "CV In %d"
#define TXT_LIST_LABEL_CV_OUT_VALUE                     "CV Out %d"
#define TXT_LIST_LABEL_MIDI                             "MIDI"
#define TXT_LIST_LABEL_CC_ABSOLUTE                      "CC Absolute"
#define TXT_LIST_LABEL_CC_RELATIVE                      "CC Relative"
#define TXT_LIST_LABEL_NOTE_MOMENTARY                   "Note Momentary"
#define TXT_LIST_LABEL_NOTE_TOGGLE                      "Note Toggle"
#define TXT_LIST_LABEL_NOTE_VELOCITY                    "Note Velocity"
#define TXT_LIST_LABEL_SCALE_SEMITONES                  "Semitones"
#define TXT_LIST_LABEL_SCALE_MAJOR                      "Major"
#define TXT_LIST_LABEL_SCALE_MINOR                      "Minor"
#define TXT_LIST_LABEL_SCALE_MAJOR_BLUES                "Major Blues"
#define TXT_LIST_LABEL_SCALE_MINOR_BLUES                "Minor Blues"
#define TXT_LIST_LABEL_SCALE_MAJOR_PENT                 "Major Pent."
#define TXT_LIST_LABEL_SCALE_MINOR_PENT                 "Minor Pent."
#define TXT_LIST_LABEL_SCALE_FOLK                       "Folk"
#define TXT_LIST_LABEL_SCALE_JAPANESE                   "Japanese"
#define TXT_LIST_LABEL_SCALE_GAMELAN                    "Gamelan"
#define TXT_LIST_LABEL_SCALE_GYPSY                      "Gypsy"
#define TXT_LIST_LABEL_SCALE_ARABIAN                    "Arabian"
#define TXT_LIST_LABEL_SCALE_FLAMENCO                   "Flamenco"
#define TXT_LIST_LABEL_SCALE_WHOLE_TONE                 "Whole Tone"
#define TXT_LIST_LABEL_SCALE_FIVE_TET                   "5-tet"
#define TXT_LIST_LABEL_SCALE_SEVEN_TET                  "7-tet"
#define TXT_LIST_LABEL_SCALE_NINETEEN_TET               "19-tet"
#define TXT_LIST_LABEL_SCALE_TWENTYTWO_TET              "22-tet"
#define TXT_LIST_LABEL_SCALE_TWENTYFOUR_TET             "24-tet"
#define TXT_LIST_LABEL_SCALE_VOLTAGE                    "Voltage"
#define TXT_LIST_LABEL_SCALE_CHROMATIC                  "Chromatic"
#define TXT_LIST_LABEL_SCALE_USER1                      "User1"
#define TXT_LIST_LABEL_SCALE_USER2                      "User2"
#define TXT_LIST_LABEL_SCALE_USER3                      "USer3"
#define TXT_LIST_LABEL_SCALE_USER4                      "User4"
#define TXT_LIST_LABEL_GATE                             "Gate"
#define TXT_LIST_LABEL_CV                               "CV"
#define TXT_LIST_LABEL_CURVE                            "Curve"
#define TXT_LIST_LABEL_MIDI_CV                          "MIDI/CV"
#define TXT_LIST_LABEL_CV_GATE                          "CV/GATE"
#define TXT_LIST_LABEL_CONDITION_OFF                    "Off"
#define TXT_LIST_LABEL_CONDITION_FILL                   "Fill"
#define TXT_LIST_LABEL_CONDITION_NOT_FILL               "!Fill"
#define TXT_LIST_LABEL_CONDITION_PRE                    "Pre"
#define TXT_LIST_LABEL_CONDITION_NOT_PRE                "!Pre"
#define TXT_LIST_LABEL_CONDITION_FIRST                  "First"
#define TXT_LIST_LABEL_CONDITION_NOT_FIRST              "!First"
#define TXT_LIST_LABEL_CONDITION_OFF_SHORT              "-"
#define TXT_LIST_LABEL_CONDITION_FILL_SHORT             "F"
#define TXT_LIST_LABEL_CONDITION_NOT_FILL_SHORT         "!F"
#define TXT_LIST_LABEL_CONDITION_PRE_SHORT              "P"
#define TXT_LIST_LABEL_CONDITION_NOT_PRE_SHORT          "!P"
#define TXT_LIST_LABEL_CONDITION_FIRST_SHORT            "1"
#define TXT_LIST_LABEL_CONDITION_NOT_FIRST_SHORT        "!1"
#define TXT_LIST_LABEL_STOPPED                          "Stopped"
#define TXT_LIST_LABEL_OVERDUB                          "Overdub"
#define TXT_LIST_LABEL_OVERWRITE                        "Overwrite"
#define TXT_LIST_LABEL_STEP_RECORD                      "Step Record"
#define TXT_LIST_LABEL_CV1_CV2                          "CV1/CV2"
#define TXT_LIST_LABEL_CV3_CV4                          "CV3/CV4"
#define TXT_LIST_LABEL_CV1                              "CV1"
#define TXT_LIST_LABEL_CV2                              "CV2"
#define TXT_LIST_LABEL_CV3                              "CV3"
#define TXT_LIST_LABEL_CV4                              "CV4"
#define TXT_LIST_LABEL_ALIGNED                          "Aligned"
#define TXT_LIST_LABEL_FREE                             "Free"
#define TXT_LIST_LABEL_FORWARD                          "Forward"
#define TXT_LIST_LABEL_BACKWARD                         "Backward"
#define TXT_LIST_LABEL_PENDULUM                         "Pendulum"
#define TXT_LIST_LABEL_PINGPONG                         "PingPong"
#define TXT_LIST_LABEL_RANDOM                           "Random"
#define TXT_LIST_LABEL_RANDOM_WALK                      "Random Walk"
#define TXT_LIST_LABEL_1V_UNIPOLAR                      "1V Unipolar"
#define TXT_LIST_LABEL_2V_UNIPOLAR                      "2V Unipolar"
#define TXT_LIST_LABEL_3V_UNIPOLAR                      "3V Unipolar"
#define TXT_LIST_LABEL_4V_UNIPOLAR                      "4V Unipolar"
#define TXT_LIST_LABEL_5V_UNIPOLAR                      "5V Unipolar"
#define TXT_LIST_LABEL_1V_BIPOLAR                       "1V Bipolar"
#define TXT_LIST_LABEL_2V_BIPOLAR                       "2V Bipolar"
#define TXT_LIST_LABEL_3V_BIPOLAR                       "3V Bipolar"
#define TXT_LIST_LABEL_4V_BIPOLAR                       "4V Bipolar"
#define TXT_LIST_LABEL_5V_BIPOLAR                       "5V Bipolar"
#define TXT_LIST_LABEL_MIDI                             "MIDI"
#define TXT_LIST_LABEL_USB                              "USB"
#define TXT_LIST_LABEL_OMNI                             "Omni"
#define TXT_LIST_LABEL_INIT                             "Init"
#define TXT_LIST_LABEL_INIT_LAYER                       "Init Layer"
#define TXT_LIST_LABEL_EUCLIDEAN                        "Euclidean"
#define TXT_LIST_LABEL_RANDOM                           "Random"
#define TXT_LIST_LABEL_ACID_BASSLINE                    "Acid Bassline"
// === Models ===
#define TXT_MODEL_MODE_PLAY_ORDER                       "Play Order"
#define TXT_MODEL_MODE_UP                               "Up"
#define TXT_MODEL_MODE_DOWN                             "Down"
#define TXT_MODEL_MODE_UP_DOWN                          "Up Down"
#define TXT_MODEL_MODE_DOWN_UP                          "Down Up"
#define TXT_MODEL_MODE_UP_AND_DOWN                      "Up & Down"
#define TXT_MODEL_MODE_DOWN_AND_UP                      "Down & Up"
#define TXT_MODEL_MODE_CONVERGE                         "Converge"
#define TXT_MODEL_MODE_DIVERGE                          "Diverge"
#define TXT_MODEL_MODE_RANDOM                           "Random"
#define TXT_MODEL_GATE_LENGTH                           "%d%%"
#define TXT_MODEL_PRINT_OCTAVE_UP_DOWN                  "Up Down %d"
#define TXT_MODEL_PRINT_OCTAVE_UP                       "Up %d"
#define TXT_MODEL_PRINT_OCTAVE_OFF                      "Off"
#define TXT_MODEL_PRINT_OCTAVE_DOWN                     "Down %d"
#define TXT_MODEL_PRINT_OCTAVE_DOWN_UP                  "Down Up %d"
#define TXT_MODEL_ITEM_TO_VOLTS_NAME                    "%+.1fV"
#define TXT_MODEL_ITEM_VALUE                            "%d"
#define TXT_MODEL_ITEM_VALUE_AUTO                       "%d (auto)"
#define TXT_MODEL_CLOCK_MODE_AUTO                       "Auto"
#define TXT_MODEL_CLOCK_MODE_MASTER                     "Master"
#define TXT_MODEL_CLOCK_MODE_SLAVE                      "Slave"
#define TXT_MODEL_CLOCK_MODE_RESET                      "Reset"
#define TXT_MODEL_CLOCK_MODE_RUN                        "Run"
#define TXT_MODEL_CLOCK_MODE_START_STOP                 "Start/Stop"
#define TXT_MODEL_CLOCK_SHIFT_MODE_RESTART              "Restart"
#define TXT_MODEL_CLOCK_SHIFT_MODE_PAUSE                "Pause"
#define TXT_MODEL_CLOCK_PULSE                           "%dms"
#define TXT_MODEL_SHAPE                                 "SHAPE"
#define TXT_MODEL_SHAPE_VARIATION                       "SHAPE VAR"
#define TXT_MODEL_SHAPE_VARIATION_PROBABILITY           "SHAPE PROB"
#define TXT_MODEL_MINIMUM                               "MIN"
#define TXT_MODEL_MAXIMUM                               "MAX"
#define TXT_MODEL_GATE                                  "GATE"
#define TXT_MODEL_GATE_PLURAL                           "Gates"
#define TXT_MODEL_GATE_PROBABILITY                      "GATE PROB"
#define TXT_MODEL_PRINT_OFF                             "off"
#define TXT_MODEL_PRINT_ALL                             "all"
#define TXT_MODEL_PRINT_ON                              "on"
#define TXT_MODEL_PRINT_BAR_COUNT                       "%d %s"
#define TXT_MODEL_PRINT_BAR                             "bar"
#define TXT_MODEL_PRINT_BAR_PLURAL                      "bars"
#define TXT_MODEL_PRINT_FIRST_STEP                      "%d"
#define TXT_MODEL_PRINT_LAST_STEP                       "%d"
#define TXT_MODEL_PRINT_VOICES                          "%d"
#define TXT_MODEL_PRINT_SEMITONES                       "%d semitones"
#define TXT_MODEL_ZERO_VOLT                             "0V"
#define TXT_MODEL_LAST_VALUE                            "Last Value"
#define TXT_MODEL_NONE                                  "None"
#define TXT_MODEL_NONE_SHORT                            "-"
#define TXT_MODEL_NA                                    "n/a"
#define TXT_MODEL_X                                     "X"
#define TXT_MODEL_VARIATION                             "Variation"
#define TXT_MODEL_NEXT_PATTERN                          "Next Pattern"
#define TXT_MODEL_INVERT                                "Invert"
#define TXT_MODEL_SLIDE_TIME                            "%d%%"
#define TXT_MODEL_TRANSPOSE                             "%+d"
#define TXT_MODEL_OCTAVE                                "%+d"
#define TXT_MODEL_VOLTAGE                               "%+.3fV"
#define TXT_MODEL_CONTROL_NUMBER                        "%d"
#define TXT_MODEL_NOTE_RANGE_VALUE                      "%d"
#define TXT_MODEL_OFFSET_VOLTAGE                        "%+.2fV"
#define TXT_MODEL_ROTATION                              "%+d"
#define TXT_MODEL_TRACK                                 "Track %d"
#define TXT_MODEL_LENGTH_BIAS                           "%+.1f%%"
#define TXT_MODEL_RETRIGGER_PROBABILITY_BIAS            "%+.1f%%"
#define TXT_MODEL_SHAPE_PROBABILITY_BIAS                "%+.1f%%"
#define TXT_MODEL_GATE_PROBABILITY_BIAS                 "%+.1f%%"
#define TXT_MODEL_NOTE_PROBABILITY_BIAS                 "%+.1f%%"
#define TXT_MODEL_GATE_PROBABILITY_VALUE                "%+.1f%%"
#define TXT_MODEL_FILL_AMOUNT                           "%d%%"
#define TXT_MODEL_TEMPO                                 "%.1f"
#define TXT_MODEL_SWING                                 "%d%%"
#define TXT_MODEL_FILE_TYPE_PROJECTS_LONG               "PROJECTS"
#define TXT_MODEL_FILE_TYPE_PROJECTS                    "PRO"
#define TXT_MODEL_FILE_TYPE_SCALES_LONG                 "SCALES"
#define TXT_MODEL_FILE_TYPE_SCALES                      "SCA"
#define TXT_MODEL_FILE_HEADER_SETTINGS                  "SETTINGS"
#define TXT_MODEL_FILE_LAST_PROJECT_FILE_NAME           "LAST.DAT"
#define TXT_MODEL_SLOT_PATH                             "%s/%03d.%s"
#define TXT_MODEL_TRIPLET_SHORTCODE                     'T'
#define TXT_MODEL_DOTTED_SHORTCODE                      '.'
#define TXT_MODEL_FULL_SHORTCODE                        '\0'
#define TXT_MODEL_GATE_VALUE                            "Gate%d"
#define TXT_MODEL_VOLTAGE_OCTAVE_VALUE                  "V/Oct%d"
#define TXT_MODEL_VELOCITY_VALUE                        "Vel%d"
#define TXT_MODEL_PRESSURE_VALUE                        "Press%d"
#define TXT_MODEL_LAST_NOTE                             "Last Note"
#define TXT_MODEL_FIRST_NOTE                            "First Note"
#define TXT_MODEL_LOWEST_NOTE                           "Lowest Note"
#define TXT_MODEL_HIGHEST_NOTE                          "Highest Note"
#define TXT_MODEL_PITCH                                 "Pitch"
#define TXT_MODEL_VELOCITY                              "Velocity"
#define TXT_MODEL_PITCH_VELOCITY                        "Pitch+Vel"
#define TXT_MODEL_PITCH_VELOCITY_PRESSURE               "Pitch+Vel+Press"
#define TXT_MODEL_NOTE                                  "Note"
#define TXT_MODEL_CC                                    "CC"
#define TXT_MODEL_NOTE_RANGE                            "NOTE RANGE"
#define TXT_MODEL_NOTE_PROBABILITY                      "NOTE PROB"
#define TXT_MODEL_NOTE_CONDITION                        "CONDITION"
#define TXT_MODEL_NOTE_LENGTH_PROBABILITY               "LENGTH PROB"
#define TXT_MODEL_NOTE_LENGTH_RANGE                     "LENGTH RANGE"
#define TXT_MODEL_NOTE_LENGTH                           "LENGTH"
#define TXT_MODEL_NOTE_RETRIGGER_PROBABILITY            "RETRIG PROB"
#define TXT_MODEL_NOTE_RETRIGGER                        "RETRIG"
#define TXT_MODEL_NOTE_SLIDE                            "SLIDE"
#define TXT_MODEL_NOTE_GATE_OFFSET                      "GATE OFFSET"
#define TXT_MODEL_DEFAULT                               "Default"
#define TXT_MODEL_ALWAYS                                "Always"
#define TXT_MODEL_NEXT_PATTERN                          "Next Pattern"
#define TXT_MODEL_INIT                                  "INIT"
#define TXT_MODEL_GENERIC_STRING                        "%s"
#define TXT_MODEL_GENERIC_VALUE                         "%d"
#define TXT_MODEL_GENERIC_CHAR                          "%c"
#define TXT_MODEL_NOTE_OCTAVE                           "%.1f"
#define TXT_MODEL_NOTE_LONG                             "%+.2fV"
#define TXT_MODEL_BEATS_STEPS                           "%d/%d"


// === UI Status ===
#define TXT_STATUS_FORMATTING_SD_CARD                   "FORMATTING SD CARD ..."
#define TXT_STATUS_SAVING_SETTINGS                      "SAVING SETTINGS ..."
#define TXT_STATUS_BACKING_UP_SETTINGS                  "BACKING UP SETTINGS ..."
#define TXT_STATUS_RESTORING_SETTINGS                   "RESTORING SETTINGS ..."
#define TXT_STATUS_LOADING_USER_SCALE                   "LOADING USER SCALE ..."
#define TXT_STATUS_SAVING_USER_SCALE                    "SAVING USER SCALE ..."
#define TXT_STATUS_LOADING_PROJECT                      "LOADING PROJECT ..."
#define TXT_STATUS_SAVING_PROJECT                       "SAVING PROJECT ..."

// === UI Interaction ===
#define TXT_PRESS_ENCODER_TO_RESET                      "PRESS ENCODER TO RESET"
#define TXT_PRESS_ENCODER_TO_RESET_TO_BOOTLOADER        "PRESS AND HOLD ENCODER TO RESET TO BOOTLOADER"
#define TXT_ENTER_NAME_PREFIX                           "NAME:"
#define TXT_ARE_YOU_SURE                                "ARE YOU SURE?"
#define TXT_REALLY_ENTER_SYSTEM_PAGE                    "DO YOU REALLY WANT TO ENTER SYSTEM PAGE?"
#define TXT_REALLY_FORMAT_SD_CARD                       "DO YOU REALLY WANT TO FORMAT THE SD CARD?"
#define TXT_TEMPO                                       "Tempo: "
#define TXT_SWING                                       "Swing: "
#define TXT_STAT_UPTIME                                 "UPTIME:"
#define TXT_STAT_MIDI_OVF                               "MIDI OVF:"
#define TXT_STAT_USBMIDI_OVF                            "USBMIDI OVF:"

// === UI Info ===
#define TXT_INFO_CLOCK_MODE_AUTO                        "A"
#define TXT_INFO_CLOCK_MODE_MANUAL                      "M"
#define TXT_INFO_CLOCK_MODE_SLAVE                       "S"
#define TXT_INFO_RECORD_MODE                            "R"
#define TXT_INFO_SNAP_MODE                              "SNAP"
#define TXT_INFO_SNAP_MODE_ACTIVE                       "S"
#define TXT_INFO_TEMPO                                  "%-1s     Í%.2f"
#define TXT_INFO_TEMPO_QUICK_ADJUST                     "%.1f%%"
#define TXT_INFO_TRACK                                  "T%d"
#define TXT_INFO_PATTERN                                "P%d"
#define TXT_INFO_EDIT_PATTERN                           "E%d"
#define TXT_INFO_SLOT_NUMBER                            "%d"
#define TXT_INFO_SLOT_ACTIVE                            "%d"
#define TXT_INFO_SLOT_INACTIVE                          "-"
#define TXT_INFO_SLOT_MUTE                              "M"
#define TXT_INFO_STEP_NUMBER                            "S%d"
#define TXT_INFO_SONG_DURATION                          "%d.%d"
#define TXT_INFO_CURRENT_MODE                           "%-s"
#define TXT_INFO_CURRENT_MODE_AND_FUNCTION              "%-s     %-s"
#define TXT_INFO_CURRENT_VERSION                        "CURRENT VERSION: %d.%d.%d"
#define TXT_INFO_VERSION_NUMBER                         "%d.%d.%d"
#define TXT_INFO_NOTE                                   "%-16s"
#define TXT_INFO_VOLTAGE                                "%.2fV"
#define TXT_INFO_CV_VALUE                               "CV%d"
#define TXT_INFO_STEP_INDEX                             "%d"
#define TXT_INFO_STEP_SELECTION_MARKER                  "*"
#define TXT_INFO_NOTE_VARIATION_RANGE                   "%d"
#define TXT_INFO_NOTE_VARIATION_PROBABILITY             "%.1f%%"
#define TXT_INFO_SHAPE_VARIATION_PROBABILITY            "%.1f%%"
#define TXT_INFO_STEP_PROBABILITY                       "%.1f%%"
#define TXT_INFO_STEP_OFFSET                            "%.1f%%"
#define TXT_INFO_STEP_RETRIGGER                         "%d"
#define TXT_INFO_STEP_RETRIGGER_PROBABILITY             "%.1f%%"
#define TXT_INFO_STEP_LENGTH                            "%.1f%%"
#define TXT_INFO_STEP_LENGTH_VARIATION_RANGE            "%.1f%%"
#define TXT_INFO_STEP_LENGTH_VARIATION_PROBABILITY      "%.1f%%"
#define TXT_INFO_MONITOR_DATA_NOTE_ON                   "CH=%d NOTE=%d VEL=%d"
#define TXT_INFO_MONITOR_DATA_NOTE_OFF                  "CH=%d NOTE=%d VEL=%d"
#define TXT_INFO_MONITOR_DATA_KEY_PRESSURE              "CH=%d NOTE=%d PRE=%d"
#define TXT_INFO_MONITOR_DATA_CONTROL_CHANGE            "CH=%d NUM=%d VAL=%d"
#define TXT_INFO_MONITOR_DATA_PROGRAM_CHANGE            "CH=%d NUM=%d"
#define TXT_INFO_MONITOR_DATA_CHANNEL_PRESSURE          "CH=%d PRE=%d"
#define TXT_INFO_MONITOR_DATA_PITCH_BEND                "CH=%d VAL=%d"
#define TXT_INFO_MONITOR_DATA_TIME_CODE                 "DATA=%02x"
#define TXT_INFO_MONITOR_DATA_SONG_POSITION             "POS=%d"
#define TXT_INFO_MONITOR_DATA_SONG_NUMBER               "NUM=%d"
#define TXT_INFO_MONITOR_DATA_UPTIME                    "%d:%02d:%02d"
#define TXT_INFO_MONITOR_DATA_MIDI_OVF                  "%d"
#define TXT_INFO_MONITOR_DATA_USBMIDI_OVF               "%d"

// These are used on song page
// TODO: Revise code to use a more generic approach
#define TXT_INFO_NUMBER                                 "#"
#define TXT_INFO_REPEATS                                "N"
#define TXT_INFO_TRACK_1                                "T1"
#define TXT_INFO_TRACK_2                                "T2"
#define TXT_INFO_TRACK_3                                "T3"
#define TXT_INFO_TRACK_4                                "T4"
#define TXT_INFO_TRACK_5                                "T5"
#define TXT_INFO_TRACK_6                                "T6"
#define TXT_INFO_TRACK_7                                "T7"
#define TXT_INFO_TRACK_8                                "T8"

// === UI Modes ===
#define TXT_MODE_USER_SCALE                             "USER SCALE"
#define TXT_MODE_TRACK                                  "TRACK"
#define TXT_MODE_SYSTEM                                 "SYSTEM"
#define TXT_MODE_SONG                                   "SONG"
#define TXT_MODE_ROUTING                                "ROUTING"
#define TXT_MODE_PROJECT                                "PROJECT"
#define TXT_MODE_PERFORMANCE                            "PERFORMER"
#define TXT_MODE_PATTERN                                "PATTERN"
#define TXT_MODE_SEQUENCE                               "SEQUENCE"
#define TXT_MODE_STEPS                                  "STEPS"
#define TXT_MODE_MONITOR                                "MONITOR"
#define TXT_MODE_MIDI_OUTPUT                            "MIDI OUTPUT"
#define TXT_MODE_LAYOUT                                 "LAYOUT"
#define TXT_MODE_GENERATOR                              "GENERATOR"
#define TXT_MODE_CLOCK                                  "CLOCK"

// === UI Functions ===
#define TXT_FUNCTION_USER_SCALE_NUMBER                  "USER%d"
#define TXT_FUNCTION_USER_SCLAE_LOAD                    "LOAD SCALE"
#define TXT_FUNCTION_USER_SCALE_SAVE                    "SAVE SCALE"
#define TXT_FUNCTION_CALIBRATION                        "CAL CV%d"
#define TXT_FUNCTION_ADVANCED_SETTING                   "ADVANCED"
#define TXT_FUNCTION_UTILITIES                          "UTILITIES"
#define TXT_FUNCTION_UPDATE                             "UPDATE"
#define TXT_FUNCTION_ROUTE                              "ROUTE %d"
#define TXT_FUNCTION_LOAD_PROJECT                       "LOAD PROJECT"
#define TXT_FUNCTION_SAVE_PROJECT                       "SAVE PROJECT"
#define TXT_FUNCTION_MONITOR_CV_IN                      "CV IN"
#define TXT_FUNCTION_MONITOR_CV_OUT                     "CV OUT"
#define TXT_FUNCTION_MONITOR_MIDI                       "MIDI"
#define TXT_FUNCTION_MONITOR_STATS                      "STATS"
#define TXT_FUNCTION_MIDI_OUTPUT_INDEX                  "OUTPUT %d"

// === Menu Buttons ===
#define TXT_MENU_INIT                                   "INIT"
#define TXT_MENU_COPY                                   "COPY"
#define TXT_MENU_PASTE                                  "PASTE"
#define TXT_MENU_LOAD                                   "LOAD"
#define TXT_MENU_SAVE                                   "SAVE"
#define TXT_MENU_SAVE_AS                                "SAVE AS"
#define TXT_MENU_ROUTE                                  "ROUTE"
#define TXT_MENU_BACKSPACE                              "BS"
#define TXT_MENU_DELETE                                 "DEL"
#define TXT_MENU_CLEAR                                  "CLEAR"
#define TXT_MENU_CANCEL                                 "CANCEL"
#define TXT_MENU_OK                                     "OK"
#define TXT_MENU_NO                                     "NO"
#define TXT_MENU_YES                                    "YES"
#define TXT_MENU_DEFAULT                                "DEFAULT"
#define TXT_MENU_AUTO                                   "AUTO"
#define TXT_MENU_COMMIT                                 "COMMIT"
#define TXT_MENU_REVERT                                 "REVERT"
#define TXT_MENU_BACKUP                                 "BACKUP"
#define TXT_MENU_RESTORE                                "RESTORE"
#define TXT_MENU_CHAIN                                  "CHAIN"
#define TXT_MENU_INSERT                                 "INSERT"
#define TXT_MENU_ADD                                    "ADD"
#define TXT_MENU_REMOVE                                 "REMOVE"
#define TXT_MENU_DUPLICATE                              "DUPL"
#define TXT_MENU_STOP                                   "STOP"
#define TXT_MENU_PLAY                                   "PLAY"
#define TXT_MENU_PREVIOUS                               "PREV"
#define TXT_MENU_NEXT                                   "NEXT"
#define TXT_MENU_LEARN                                  "LEARN"
#define TXT_MENU_LATCH                                  "LATCH"
#define TXT_MENU_SYNC                                   "SYNC"
#define TXT_MENU_UNMUTE                                 "UNMUTE"
#define TXT_MENU_FILL                                   "FILL"
#define TXT_MENU_SNAP                                   "SNAP"
#define TXT_MENU_MAPS                                   "MAP"
#define TXT_MENU_GATES                                  "GATE"
#define TXT_MENU_NOTES                                  "NOTE"
#define TXT_MENU_VOLTAGES                               "VOLTAGE"
#define TXT_MENU_GENERATORS                             "GEN"
#define TXT_MENU_GATES                                  "GATE"
#define TXT_MENU_RETRIGGERS                             "RETRIG"
#define TXT_MENU_LENGTHS                                "LENGTH"
#define TXT_MENU_CONDITIONS                             "COND"
#define TXT_MENU_MODE                                   "MODE"
#define TXT_MENU_LINK                                   "LINK"
#define TXT_MENU_CV                                     "CV"
#define TXT_MENU_SHAPE                                  "SHAPE"
#define TXT_MENU_MINIMUM                                "MIN"
#define TXT_MENU_MAXIMUM                                "MAX"
#define TXT_MENU_SEED                                   "SEED"
#define TXT_MENU_ROOT                                   "ROOT"
#define TXT_MENU_LENGTH                                 "LENGTH"
#define TXT_MENU_DENSITY                                "DENSITY"
#define TXT_MENU_LEGATO                                 "LEGATO"
#define TXT_MENU_STEPS                                  "STEPS"
#define TXT_MENU_BEATS                                  "BEATS"
#define TXT_MENU_OFFSET                                 "OFFSET"
#define TXT_MENU_SCALE                                  "SCALE"
#define TXT_MENU_BIAS                                   "BIAS"
#define TXT_MENU_SMOOTH                                 "SMOOTH"

#define TXT_MENU_USER_SCALE_1                           "USER1"
#define TXT_MENU_USER_SCALE_2                           "USER2"
#define TXT_MENU_USER_SCALE_3                           "USER3"
#define TXT_MENU_USER_SCALE_4                           "USER4"

#define TXT_MENU_SYSTEM_CALIBRATION                     "CAL"
#define TXT_MENU_SYSTEM_ADVANCED                        "ADVANCED"
#define TXT_MENU_SYSTEM_UTILS                           "UTILS"
#define TXT_MENU_SYSTEM_UPDATE                          "UPDATE"

// === Events ===
#define TXT_EVENT_NOTE_ON                               "NOTE ON"
#define TXT_EVENT_NOTE_OFF                              "NOTE OFF"
#define TXT_EVENT_KEY_PRESSURE                          "KEY PRESSURE"
#define TXT_EVENT_CONTROL_CHANGE                        "CONTROL CHANGE"
#define TXT_EVENT_PROGRAM_CHANGE                        "PROGRAM CHANGE"
#define TXT_EVENT_CHANNEL_PRESSURE                      "CHANNEL PRESSURE"
#define TXT_EVENT_PITCH_BEND                            "PITCH BEND"
#define TXT_EVENT_SYSEX                                 "SYSEX"
#define TXT_EVENT_TIME_CODE                             "TIME CODE"
#define TXT_EVENT_SONG_POSITION                         "SONG POSITION"
#define TXT_EVENT_SONG_SELECT                           "SONG SELECT"


#define TXT_EVENT_TUNE_REQUEST                          "TUNE REQUEST"

// === Errors ===
#define TXT_ERROR_FATAL_ERROR                           "FATAL ERROR"
#define TXT_ERROR_FAILED                                "FAILED (%s)"
#define TXT_ERROR_INVALID_USER_SCALE_FILE               "INVALID USER SCALE FILE"
#define TXT_ERROR_INVALID_SETTINGS_FILE                 "INVALID SETTING FILE"
#define TXT_ERROR_INVALID_PROJECT_FILE                  "INVALID PROJECT FILE"

// === Asteroids Easter Egg ===
#define TXT_ASTEROIDS_INTRO                             "ASTEROIDS", "Press any f-key to continue"
#define TXT_ASTEROIDS_LEVEL                             "LEVEL %d"
#define TXT_ASTEROIDS_PRESS_ANY_KEY                     "Press any f-key to continue"
#define TXT_ASTEROIDS_WIN                               "YOU WIN!"
#define TXT_ASTEROIDS_LOSE                              "YOU LOSE!"
#define TXT_ASTEROIDS_SCORE                             "Score %d"